fix: delete image in ghcr

diff --git a/.github/workflows/build_and_test.yaml b/.github/workflows/build_and_test.yaml
--- a/.github/workflows/build_and_test.yaml
+++ b/.github/workflows/build_and_test.yaml
@@ -52,133 +52,133 @@ env:
   COMMIT_ID: ${{ inputs.commit_id || github.sha }}
 
 jobs:  
-  # build:
-  #   if: github.event_name == 'push' || github.event_name == 'pull_request' || (inputs.run_build && github.event_name == 'workflow_dispatch')
-  #   runs-on: ubuntu-dind
-  #   permissions:
-  #     contents: read
-  #     packages: write
-  #   steps:
-  #   - name: Validate image tag
-  #     if: github.event_name == 'workflow_dispatch'
-  #     id: validate_dispatch_inputs
-  #     run: |
-  #       if [[ "${{ inputs.image_tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ || "${{ inputs.image_tag }}" == "latest" ]]; then
-  #         echo "is_image_tag_valid=false" >> $GITHUB_OUTPUT
-  #         echo "You CAN NOT build image with tag ${{ inputs.image_tag }} with manual trigger. Skipping the rest of the build job..."
-  #       else
-  #         echo "is_image_tag_valid=true" >> $GITHUB_OUTPUT
-  #       fi
+  build:
+    if: github.event_name == 'push' || github.event_name == 'pull_request' || (inputs.run_build && github.event_name == 'workflow_dispatch')
+    runs-on: ubuntu-dind
+    permissions:
+      contents: read
+      packages: write
+    steps:
+    - name: Validate image tag
+      if: github.event_name == 'workflow_dispatch'
+      id: validate_dispatch_inputs
+      run: |
+        if [[ "${{ inputs.image_tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ || "${{ inputs.image_tag }}" == "latest" ]]; then
+          echo "is_image_tag_valid=false" >> $GITHUB_OUTPUT
+          echo "You CAN NOT build image with tag ${{ inputs.image_tag }} with manual trigger. Skipping the rest of the build job..."
+        else
+          echo "is_image_tag_valid=true" >> $GITHUB_OUTPUT
+        fi
 
-  #   - name: Checkout code
-  #     if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
-  #     uses: actions/checkout@v4
-  #     with:
-  #       ref: ${{ env.COMMIT_ID }}
+    - name: Checkout code
+      if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ env.COMMIT_ID }}
 
-  #   - name: Build Docker image
-  #     if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
-  #     run: |
-  #       echo ${{ steps.validate_dispatch_inputs.outputs.is_image_tag_valid }}
-  #       docker build --build-arg git_token=${{ secrets.GITHUB_TOKEN }} --build-arg CACHEBUST=$(date +%s) --build-arg BRANCH=main --build-arg OWNER=${{ github.repository_owner }} -t ${{ env.IMAGE_NAME }} .
+    - name: Build Docker image
+      if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
+      run: |
+        echo ${{ steps.validate_dispatch_inputs.outputs.is_image_tag_valid }}
+        docker build --build-arg git_token=${{ secrets.GITHUB_TOKEN }} --build-arg CACHEBUST=$(date +%s) --build-arg BRANCH=main --build-arg OWNER=${{ github.repository_owner }} -t ${{ env.IMAGE_NAME }} .
 
-  #   - id: run_and_check_container_status
-  #     if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
-  #     name: Run Tender app
-  #     uses: svtechnmaa/.github/actions/run_docker_container@main
-  #     with:
-  #       imageName: '${{ env.IMAGE_NAME }}'
-  #       containerName: '${{ env.CONTAINER_NAME }}'
-  #       containerMappingPort: '${{ env.CONTAINER_MAPPING_PORT }}'
+    - id: run_and_check_container_status
+      if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
+      name: Run Tender app
+      uses: svtechnmaa/.github/actions/run_docker_container@main
+      with:
+        imageName: '${{ env.IMAGE_NAME }}'
+        containerName: '${{ env.CONTAINER_NAME }}'
+        containerMappingPort: '${{ env.CONTAINER_MAPPING_PORT }}'
 
-  #   - name: Downcase REPO
-  #     if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
-  #     run: |
-  #       echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+    - name: Downcase REPO
+      if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
+      run: |
+        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
 
-  #   - name: Login to GitHub Container Registry
-  #     if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
-  #     uses: docker/login-action@v2
-  #     with:
-  #       registry: ghcr.io
-  #       username: '${{ github.repository_owner }}'
-  #       password: '${{ secrets.GITHUB_TOKEN }}'
+    - name: Login to GitHub Container Registry
+      if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
+      uses: docker/login-action@v2
+      with:
+        registry: ghcr.io
+        username: '${{ github.repository_owner }}'
+        password: '${{ secrets.GITHUB_TOKEN }}'
         
-  #   - name: Push image to GitHub Container Registry
-  #     if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
-  #     run: |
-  #       docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
-  #       docker push ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
+    - name: Push image to GitHub Container Registry
+      if: github.event_name == 'push' || github.event_name == 'pull_request' || steps.validate_dispatch_inputs.outputs.is_image_tag_valid == 'true'
+      run: |
+        docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
+        docker push ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
 
-  # test: 
-  #   # add always() to prevent needs previous job if it is cancelled by manual trigger
-  #   # add !cancelled() and !failure to prevent always()
-  #   if: |
-  #     ( github.event_name == 'push' && !cancelled() && !failure() ) || 
-  #     ( github.event_name == 'pull_request' && !cancelled() && !failure() ) || 
-  #     ( github.event_name == 'workflow_dispatch' && inputs.run_test && always() && !cancelled() && !failure() )
-  #   needs: build
-  #   runs-on: robot-dind
-  #   permissions:
-  #     contents: read
-  #     packages: write
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ env.COMMIT_ID }}
+  test: 
+    # add always() to prevent needs previous job if it is cancelled by manual trigger
+    # add !cancelled() and !failure to prevent always()
+    if: |
+      ( github.event_name == 'push' && !cancelled() && !failure() ) || 
+      ( github.event_name == 'pull_request' && !cancelled() && !failure() ) || 
+      ( github.event_name == 'workflow_dispatch' && inputs.run_test && always() && !cancelled() && !failure() )
+    needs: build
+    runs-on: robot-dind
+    permissions:
+      contents: read
+      packages: write
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ env.COMMIT_ID }}
 
-  #     - name: Downcase REPO
-  #       run: |
-  #         echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+      - name: Downcase REPO
+        run: |
+          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
 
-  #     - name: Login to GitHub Container Registry
-  #       uses: docker/login-action@v2
-  #       with:
-  #         registry: ghcr.io
-  #         username: '${{ github.repository_owner }}'
-  #         password: '${{ secrets.GITHUB_TOKEN }}'
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: '${{ github.repository_owner }}'
+          password: '${{ secrets.GITHUB_TOKEN }}'
           
-  #     - name: Pull image from GitHub Container Registry
-  #       run: |
-  #         docker pull ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
+      - name: Pull image from GitHub Container Registry
+        run: |
+          docker pull ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}
 
-  #     - id: run_and_check_container_status
-  #       name: Run Tender app
-  #       uses: svtechnmaa/.github/actions/run_docker_container@main
-  #       with:
-  #         imageName: 'ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}'
-  #         containerName: '${{ env.CONTAINER_NAME }}'
-  #         containerMappingPort: '${{ env.CONTAINER_MAPPING_PORT }}'
+      - id: run_and_check_container_status
+        name: Run Tender app
+        uses: svtechnmaa/.github/actions/run_docker_container@main
+        with:
+          imageName: 'ghcr.io/${{ env.REPO }}:${{ env.IMAGE_TAG }}'
+          containerName: '${{ env.CONTAINER_NAME }}'
+          containerMappingPort: '${{ env.CONTAINER_MAPPING_PORT }}'
           
-  #     - name: Run Robot Framework tests
-  #       run: |
-  #         echo "##[command]robot tests/"
-  #         robot tests/
+      - name: Run Robot Framework tests
+        run: |
+          echo "##[command]robot tests/"
+          robot tests/
 
-  #     - name: Delete package from GHCR if test fails
-  #       if: failure() && !inputs.keep_image 
-  #       run: |
-  #         if [[ "${{ env.IMAGE_TAG }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ || "${{ env.IMAGE_TAG }}" == "latest" ]]; then
-  #           echo "Image with tag ${{ env.IMAGE_TAG }} must NOT be deleted."
-  #         else
-  #           echo "Robot test failed, deleting package from GHCR..."
-  #           REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
-  #           echo "Repo name: $REPO_NAME"
-  #           VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" | jq -r '.[] | select(.metadata.container.tags[] == "${{ env.IMAGE_TAG }}") | .id')
-  #           echo "Package version ID: $VERSION_ID"
-  #           curl -i -X DELETE -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
-  #         fi
+      - name: Delete package from GHCR if test fails
+        if: failure() && !inputs.keep_image 
+        run: |
+          if [[ "${{ env.IMAGE_TAG }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ || "${{ env.IMAGE_TAG }}" == "latest" ]]; then
+            echo "Image with tag ${{ env.IMAGE_TAG }} must NOT be deleted."
+          else
+            echo "Robot test failed, deleting package from GHCR..."
+            REPO_NAME=$(echo ${{ env.REPO }} | cut -d'/' -f2)
+            echo "Repo name: $REPO_NAME"
+            VERSION_ID=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions" | jq -r '.[] | select(.metadata.container.tags[] == "${{ env.IMAGE_TAG }}") | .id')
+            echo "Package version ID: $VERSION_ID"
+            curl -i -X DELETE -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -H "Accept: application/vnd.github.v3+json" "https://api.github.com/users/${{ github.repository_owner }}/packages/container/$REPO_NAME/versions/$VERSION_ID"
+          fi
 
-  #     - name: 'Upload Artifact'
-  #       if: always()
-  #       uses: actions/upload-artifact@v4.6.0
-  #       with:
-  #         name: robot-test-result-#${{ github.run_number }}
-  #         path: |
-  #           ./output.xml
-  #           ./log.html
-  #           ./report.html
+      - name: 'Upload Artifact'
+        if: always()
+        uses: actions/upload-artifact@v4.6.0
+        with:
+          name: robot-test-result-#${{ github.run_number }}
+          path: |
+            ./output.xml
+            ./log.html
+            ./report.html
 
 
   release:
