fix: modify condition for send mail

diff --git a/.github/workflows/build_and_test.yaml b/.github/workflows/build_and_test.yaml
--- a/.github/workflows/build_and_test.yaml
+++ b/.github/workflows/build_and_test.yaml
@@ -85,10 +85,17 @@ jobs:
         echo "job_id=$(cat job_id.txt)" >> $GITHUB_OUTPUT
 
     - name: Scan Dockerfile 
-      run: trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
+      id: scan_dockerfile
+      run: |
+        trivy config --severity HIGH,CRITICAL --format table --output dockerfile_scanning_result.json --exit-code 1 ./Dockerfile
+        
+        if [[ $? -ne 0 ]]; then
+          echo "SCANNING_DOCKERFILE_FAILED=true" >> $GITHUB_OUTPUT
+        fi
       continue-on-error: true
       
     - name: Send mail to committer if detect vulnerability in Dockerfile
+      if: steps.scan_dockerfile.outputs.SCANNING_DOCKERFILE_FAILED == 'true'
       uses: dawidd6/action-send-mail@v4
       with:
         server_address: smtp.gmail.com
@@ -134,10 +141,17 @@ jobs:
         containerMappingPort: '${{ env.CONTAINER_MAPPING_PORT }}'
 
     - name: Scan Docker image
-      run: trivy image --server http://10.98.15.6:7777 --severity HIGH,CRITICAL --format table --output image_scanning_result.json --exit-code 1 ${{ env.IMAGE_NAME }}:latest
+      id: scan_docker_image
+      run: |
+        trivy image --server http://10.98.15.6:7777 --severity HIGH,CRITICAL --format table --output image_scanning_result.json --exit-code 1 ${{ env.IMAGE_NAME }}:latest
+
+        if [[ $? -ne 0 ]]; then
+          echo "SCANNING_IMAGE_FAILED=true" >> $GITHUB_OUTPUT
+        fi
       continue-on-error: true
 
     - name: Send mail to committer if detect vulnerability in Docker image
+      if: steps.scan_docker_image.outputs.SCANNING_IMAGE_FAILED == 'true'
       uses: dawidd6/action-send-mail@v4
       with:
         server_address: smtp.gmail.com
